version: '3.3'

services:
  marriage-php:
    container_name: marriage-php
    build:
      ./etc/php/.
    volumes:
     - ./www/:/app
     - ./etc/php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
    working_dir: /app
    stdin_open: true
    tty: true
networks:
  default:
    external:
      name: test-php8-network
